[package]
name = "edinburgh"
version = "0.0.1"
edition = "2021"

[dependencies]
colog = "1.3.0"
log = "0.4.26"
# https://lib.rs/crates/nix/features
nix = { version = "0.29.0", features = ["fs", "poll"] }
