[package]
name = "edinburgh"
version = "0.0.1"
edition = "2021"
default-run = "edinburgh"

[dependencies]
access-unit = "0.1.0"
bytemuck = "1.22.0"
bytes = "1.10.1"
colog = "1.3.0"
derivative = "2.2.0"
faad2 = "0.1.0"
fdk-aac-sys = "0.5.0"
futures = "0.3.31"
log = "0.4.26"
nix = { version = "0.29.0", features = ["fs", "poll"] }
rodio = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "sync"] }
tungstenite = "0.26.2"

[[bin]]
name = "edinburgh"
path = "src/main.rs"

[[bin]]
name = "edinburgh-sync"
path = "src/main_sync.rs"
